version: '3.8'

services:
  python-app:
    build:
      context: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE=/database/testDB.db
    volumes:
      - "./:/app"
    ports:
      - ${APPLICATION_PORT}:5000